diff  aprod.f90 ../../../TOMOTV_HFM_PL/SRC_OCTOBER_2022/INVERSE_TV_SMOOTH_gradient/aprod.f90
diff  inverse.tomo.f90 ../../../TOMOTV_HFM_PL/SRC_OCTOBER_2022/INVERSE_TV_SMOOTH_gradient/inverse.tomo.f90
diff  lsqrblas.f90 ../../../TOMOTV_HFM_PL/SRC_OCTOBER_2022/INVERSE_TV_SMOOTH_gradient/lsqrblas.f90
diff  lsqr.f90 ../../../TOMOTV_HFM_PL/SRC_OCTOBER_2022/INVERSE_TV_SMOOTH_gradient/lsqr.f90
diff  new_parameters_denoising2D.f90 ../../../TOMOTV_HFM_PL/SRC_OCTOBER_2022/INVERSE_TV_SMOOTH_gradient/new_parameters_denoising2D.f90
diff  new_parameters.f90 ../../../TOMOTV_HFM_PL/SRC_OCTOBER_2022/INVERSE_TV_SMOOTH_gradient/new_parameters.f90
diff  new_parameters_old.f90 ../../../TOMOTV_HFM_PL/SRC_OCTOBER_2022/INVERSE_TV_SMOOTH_gradient/new_parameters_old.f90
diff  new_parameters_smoothing_only_old.f90 ../../../TOMOTV_HFM_PL/SRC_OCTOBER_2022/INVERSE_TV_SMOOTH_gradient/new_parameters_smoothing_only_old.f90
diff  read_matrix.f90 ../../../TOMOTV_HFM_PL/SRC_OCTOBER_2022/INVERSE_TV_SMOOTH_gradient/read_matrix.f90
diff  sub_nesterov_3D.f90 ../../../TOMOTV_HFM_PL/SRC_OCTOBER_2022/INVERSE_TV_SMOOTH_gradient/sub_nesterov_3D.f90
diff  sub_read.f90 ../../../TOMOTV_HFM_PL/SRC_OCTOBER_2022/INVERSE_TV_SMOOTH_gradient/sub_read.f90
diff  sub_smoothing.f90 ../../../TOMOTV_HFM_PL/SRC_OCTOBER_2022/INVERSE_TV_SMOOTH_gradient/sub_smoothing.f90
diff  tt.f90 ../../../TOMOTV_HFM_PL/SRC_OCTOBER_2022/INVERSE_TV_SMOOTH_gradient/tt.f90
